### ISSUE TITLE
Double pressed keys are not recognized

### ISSUE THREAD

**Issue by Leevy27** [jayanam/shortcut_VUr#11]
Hi Jayanam,
You closed this feature 4 days ago but it is only working in object mode. If you are in edit mode and you are marking an edge, pressing GG twice it is only displaying one G.

In object mode, if you are pressing twice GG fast, it shows you Gx3. If you press it not so fast, then it shows you Gx2.

**Comment by RoujinX** [comment]
Actually, this should be recognized as something separate, because it also represents separate functionality. 

For example Ax3 isn't the same thing as double tap A, but double tap A is always displayed as such. This seems to suggest the addon already detects this as different to just pressing the A key merely twice. If that's the case the screencast should also reflect that. Maybe actually use the word "double" as a prefix instead? So this would be "double A" instead of Ax3. Same would apply to another instance were double tapping can be used in blender; "double G", "double R", etc.

**Comment by jayanam** [comment]
Hey, no the addon doesnt reflect this. It only displays the keys that are sent to the callback function, which are different for special use-cases. For exmaple in edit mode the addon gets the first G press, then a modifier is active and the addon doesnt receive any keys at all.
